version: "3.8"

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
      - ollama
      - vllm
    env_file:
      - .env

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3307"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - streamlit

  ollama:
    image: ollama/ollama
    restart: always
    ports:
      - "11434:11434"

  vllm:
    image: vllm/vllm-openai:latest
    restart: always
    ports:
      - "8000:8000"
    command: >
      --model mistralai/Mistral-7B-v0.1
    environment:
      - "HUGGING_FACE_HUB_TOKEN=<your_token>"

volumes:
  mysql_data:
